# Generated by Django 2.2.1 on 2019-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=20)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
